version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.src
    ports:
      - "8000:8000"
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USER: root
      MONGO_PASSWORD: example
      MONGO_DB: perfume_db
    depends_on:
      - scripts
      - mongodb

  scripts:
    build:
      context: .
      dockerfile: Dockerfile.scripts
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USER: root
      MONGO_PASSWORD: example
      MONGO_DB: perfume_db
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/scripts/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo_data: