name: Run Tests and Coverage Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pip and dependencies
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Verify pytest is available
        run: |
          which pytest
          pytest --version

      - name: Run tests and check coverage
        run: |
          COVERAGE_OUTPUT=$(pytest --cov=src --cov-report=term-missing)
          echo "$COVERAGE_OUTPUT"

          COVERAGE_PERCENT=$(echo "$COVERAGE_OUTPUT" | grep TOTAL | awk '{print $NF}' | sed 's/%//')
          MIN_COVERAGE=70

          if (( $(echo "$COVERAGE_PERCENT < $MIN_COVERAGE" | bc -l) )); then
            echo "❌ Coverage is below the expected threshold ($MIN_COVERAGE%). Actual: $COVERAGE_PERCENT%"
            exit 1
          else
            echo "✅ Coverage is sufficient: $COVERAGE_PERCENT%"
          fi
