name: Run Tests and Check Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          source venv/bin/activate
          pytest --maxfail=1 --disable-warnings -q --cov=src --cov-report=xml

      - name: Check coverage
        run: |
          COVERAGE_OUTPUT=$(pytest --cov=src --cov-report=term-missing)
          echo "$COVERAGE_OUTPUT"
          COVERAGE_PERCENT=$(echo "$COVERAGE_OUTPUT" | grep TOTAL | awk '{print $NF}' | sed 's/%//')
          MIN_COVERAGE=70
      
          if (( $(echo "$COVERAGE_PERCENT < $MIN_COVERAGE" | bc -l) )); then
            echo "❌ Coverage is below the expected threshold ($MIN_COVERAGE%). Actual: $COVERAGE_PERCENT%"
            exit 1
          else
            echo "✅ Coverage is sufficient: $COVERAGE_PERCENT%"
          fi
